### PR TITLE
Ensure TCK passes with empty publisher that synchronously completes

### LINKED ISSUE #422: PublisherVerification.optional_spec105_emptyStreamMustTerminateBySignallingOnComplete fails if the publisher completes synchronously
Consider the following empty publisher:

```java
class EmptyPublisher implements Publisher<Void> {
  public void subscribe(Subscriber<? super Void> subscriber) {
    Objects.requireNonNull(subscriber);
    subscriber.onSubscribe(new Subscription() { ... });
    subscriber.onComplete();
  }
}
```

I believe this is a valid publisher according to the spec, there's nothing that says that `onComplete` can't be synchronously invoked from `subscribe`, it just has to be invoked after `onSusbscribe` (it is). 

However `PublisherVerification.optional_spec105_emptyStreamMustTerminateBySignallingOnComplete`, a test for empty publishers which should pass on the above publisher, fails with `java.lang.AssertionError: Subscriber::onComplete() called before Subscriber::onSubscribe`.

The problem seems to be that `ManualSubscriberWithSubscriptionSupport` requires `expectCompletion` to be invoked after `onSubscribe` and before `onComplete` is invoked. But `expectCompletion` isn't invoked until after `subscribe` returns, hence synchronous invocation of `onComplete` after `onSusbcribe` in  the `subscribe` method will always fail.

### PR DESCRIPTION
**Pull request by jroper**
Fixes #422

### CODE REVIEW

File: tck/src/main/java/org/reactivestreams/tck/TestEnvironment.java [hunk 1]
```diff
@@ -599,6 +602,7 @@ public void onSubscribe(Subscription s) {
       env.debug(String.format("%s::onSubscribe(%s)", this, s));
       if (!subscription.isCompleted()) {
         subscription.complete(s);
```
Comment (akarnokd) [inline tck/src/main/java/org/reactivestreams/tck/TestEnvironment.java]: There is a [completeImmediately()](https://github.com/reactive-streams/reactive-streams-jvm/blob/master/tck/src/main/java/org/reactivestreams/tck/TestEnvironment.java#L910) method on the promise.

Comment (akarnokd) [reply tck/src/main/java/org/reactivestreams/tck/TestEnvironment.java]: Btw. the plain `complete()` behavior is odd. I'd think once called, `isCompleted()` should report true but the implementation queues the object.

Comment (jroper) [reply tck/src/main/java/org/reactivestreams/tck/TestEnvironment.java]: I agree - but I'm not familiar enough with the TCK to change it. Though I can understand why the event is queued, so that the order of events can be verified and duplicates can be detected etc.

**Comment by jroper** [comment]
I thought about changing `onNext`, however, the manual subscriber will never invoke `Subscription.request` before invoking `expectCompletion`, so I think that logic is still valid, even if the error message is a little odd. My worry with changing it is that there might be some tests that depend on the current behaviour.

File: tck/src/test/java/org/reactivestreams/tck/flow/support/TCKVerificationSupport.java [hunk 2]
```diff
@@ -81,6 +81,18 @@ public void requireTestSkip(ThrowingRunnable run, String msgPart) {
     throw new RuntimeException("Expected TCK to SKIP this test, instead if PASSed!");
   }
 
+  public void requireOptionalTestPass(ThrowingRunnable run) {
+    try {
+      run.run();
+    } catch (SkipException skip) {
+      throw new RuntimeException("Expected TCK to PASS this test, instead it was SKIPPED", skip.getCause());
+    } catch (Throwable throwable) {
+      throw new RuntimeException(
```
Comment (viktorklang) [inline tck/src/test/java/org/reactivestreams/tck/flow/support/TCKVerificationSupport.java]: Repackage Errors as Exceptions?

Comment (jroper) [reply tck/src/test/java/org/reactivestreams/tck/flow/support/TCKVerificationSupport.java]: Just being consistent with `requireTestFailure` and `requireTestSkip`.

File: tck/src/main/java/org/reactivestreams/tck/TestEnvironment.java (hunk 1 above)
Comment (ktoso) [reply tck/src/main/java/org/reactivestreams/tck/TestEnvironment.java]: I'll investigate this

File: tck/src/test/java/org/reactivestreams/tck/flow/support/TCKVerificationSupport.java (hunk 2 above)
Comment (ktoso) [reply tck/src/test/java/org/reactivestreams/tck/flow/support/TCKVerificationSupport.java]: Does not really matter much as those will end up failing the test in the suite and one may always look into the logs. It's not like it's a production app where we have to watch out to not accidentally continue after an OOM or something... Fine as is I think

File: tck/src/main/java/org/reactivestreams/tck/TestEnvironment.java (hunk 1 above)
Comment (ktoso) [reply tck/src/main/java/org/reactivestreams/tck/TestEnvironment.java]: Thanks for noticing, I think we can improve the impl there. I'll work on it today after done with work stuff.
I'll PR into this PR then :)

**Comment by ktoso** [comment]
I submitted an impl improvement of the Promise which makes the test pass the new requirement: 
https://github.com/jroper/reactive-streams-jvm/pull/1

I submitted the change as PR into this PR, so if you accept it over there @jroper we could merge all those commits rebased here together I guess.

File: tck/src/main/java/org/reactivestreams/tck/TestEnvironment.java (hunk 1 above)
Comment (ktoso) [reply tck/src/main/java/org/reactivestreams/tck/TestEnvironment.java]: I reimplemented the Promise which makes this workwithout the additional atomic.
Please see here: https://github.com/jroper/reactive-streams-jvm/pull/1

**Comment by viktorklang** [comment]
@jroper @ktoso Hey all, I just wanted to know what the current status is here.

**Comment by ktoso** [comment]
I would like @jroper to merge the fix I proposed to this PR, it's been waiting ;-)

**Comment by ktoso** [comment]
PR was merged, thanks @jroper ! Seems good to go from my side then

**Comment by viktorklang** [comment]
thanks @jroper!
